# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['@all']
   'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kirigami': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/kdbusaddons': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'frameworks/knewstuff': '@latest-kf6'
    'frameworks/knotifications': '@latest-kf6'
    'frameworks/ksvg': '@latest-kf6'
    'frameworks/kwindowsystem': '@latest-kf6'
    'frameworks/kjobwidgets': '@latest-kf6'
    'frameworks/kuserfeedback': '@latest-kf6'
    'frameworks/kcmutils': '@latest-kf6'
    'plasma/libplasma': '@same'
    'plasma/milou': '@same'
    'libraries/kirigami-addons': '@latest-kf6'

runtime-dependencies:
 'plasma/plasma5support': '@same'
 'plasma/plasma-nm': '@same'

Options:
 require-passing-tests-on: ['Linux', 'FreeBSD']
 run-qmllint: true
