version = 1
SPDX-PackageName = "plasma-welcome"
SPDX-PackageSupplier = "Nate Graham <nate@kde.org>"
SPDX-PackageDownloadLocation = "https://invent.kde.org/plasma/plasma-welcome"

[[annotations]]
path = "src/assets/konqi-kde-hi.png"
precedence = "aggregate"
SPDX-FileCopyrightText = "2014 Tyson Tan <tysontan@mail.com>"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = "src/assets/konqi-default.png"
precedence = "aggregate"
SPDX-FileCopyrightText = "2014 Tyson Tan <tysontan@mail.com>"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = "src/assets/blender.svg"
precedence = "aggregate"
SPDX-FileCopyrightText = "2010 Blender Foundation <foundation@blender.org>"
SPDX-License-Identifier = "GPL-2.0-only"

[[annotations]]
path = "src/assets/endlesssky.png"
precedence = "aggregate"
SPDX-FileCopyrightText = "2016 Michael Zahniser <mzahniser@gmail.com>"
SPDX-License-Identifier = "GPL-3.0-only"

[[annotations]]
path = "src/assets/gimp.svg"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Aryeom Han <aryeom@gimp.org>"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = "src/assets/krita.svg"
precedence = "aggregate"
SPDX-FileCopyrightText = "2021 Timothée Giet <animtim@gmail.com>"
SPDX-License-Identifier = "GPL-3.0-only"

[[annotations]]
path = "src/assets/kstars.svg"
precedence = "aggregate"
SPDX-FileCopyrightText = "2007 Nuno Pinheiro <nuno@oxygen-icons.org>"
SPDX-License-Identifier = "GPL-3.0-only"

[[annotations]]
path = "src/assets/vlc.png"
precedence = "aggregate"
SPDX-FileCopyrightText = "1996-2010 VideoLAN <videolan@videolan.org>"
SPDX-License-Identifier = "GPL-2.0-only"

[[annotations]]
path = "src/kded/kded_plasma-welcome.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 Oliver Beard <olib141@outlook.com>"
SPDX-License-Identifier = "GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL"
